readme-updates
graphaelli/zat pull request #27
Opened 2020-12-23 07:15 UTC by matschaffer

2020-12-23 08:00 UTC, ruflin approved these changes
LGTM. It has been a while since I set it up so didn't go through the flow but what you put down here makes a lot of sense.

2020-12-23 08:02 UTC, matschaffer commented
Thanks! Looks like I lack a merge button here so will leave it to you or @graphaelli

2020-12-23 08:04 UTC, ruflin commented
No merge button for me either 😢

2020-12-23 17:22 UTC, graphaelli requested changes

2020-12-23 17:22 UTC, graphaelli commented on README.md
> +    * Name it "zat"
```suggestion
```

2020-12-26 16:18 UTC, graphaelli approved these changes
Thanks!

2020-12-26 16:18 UTC, merged